// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCMsmnEJSCdnAcr5wjuuQJO1vgumOahbk',
    appId: '1:212124285478:web:a5d0bda48010265f3ac4e7',
    messagingSenderId: '212124285478',
    projectId: 'chatapplication-36f74',
    authDomain: 'chatapplication-36f74.firebaseapp.com',
    storageBucket: 'chatapplication-36f74.appspot.com',
    measurementId: 'G-58CEVV21KD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjX14V-2LyXWzn-B57BrpFVvEwwczo4Pk',
    appId: '1:212124285478:android:c36d4f167d6a7c453ac4e7',
    messagingSenderId: '212124285478',
    projectId: 'chatapplication-36f74',
    storageBucket: 'chatapplication-36f74.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWs1CyXwyfwuihtITE_KLJcpUtc5OJQ1Q',
    appId: '1:212124285478:ios:bc017c78deb135dc3ac4e7',
    messagingSenderId: '212124285478',
    projectId: 'chatapplication-36f74',
    storageBucket: 'chatapplication-36f74.appspot.com',
    iosClientId:
        '212124285478-08gv2iknepsldbibv66lsc06rt512r6h.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectmockpage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWs1CyXwyfwuihtITE_KLJcpUtc5OJQ1Q',
    appId: '1:212124285478:ios:bc017c78deb135dc3ac4e7',
    messagingSenderId: '212124285478',
    projectId: 'chatapplication-36f74',
    storageBucket: 'chatapplication-36f74.appspot.com',
    iosClientId:
        '212124285478-08gv2iknepsldbibv66lsc06rt512r6h.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectmockpage',
  );
}
